### ISSUE TITLE
Is it Swift 4.1?

### ISSUE THREAD

**Issue by MihaelIsaev** [SwiftJava/android_toolchain#1]
Hey, thanks for your work!

Is it correct that v4.1 of the android-toolchain means that it is Swift 4.1?

If so then could we have Swift 5.2 version of this? 🙂

**Comment by johnno1962** [comment]
4.1 is the last version I produced. There are other people producing Android toolchains now notably https://github.com/readdle/swift-android-toolchain

**Comment by MihaelIsaev** [comment]
@johnno1962 thank you for the response! I really appreciate! Could you tell if you still building apps in Swift for Android? it seems that there are no one who's doing it nowadays. I'm speaking especially about building UI using Swift. As far as I know Readdle guys use Swift just to put their core-logic to android, but they use classic kotlin/java+xml to build the UI and android-specific things.

**Comment by johnno1962** [comment]
I'm not personally and the UI side of is better done the classic way for Android. The port was intended for core logic.
